export const SKILLS = {
    js: 'JavaScript',
    ts: 'TypeScript',
    react: 'React.js',
    next: 'Next.js',
    redux: 'Redux',
    node: 'Node.js',
    nextAuth: 'NextAuth',
    auth: 'Auth.js',
    awsAmplify: 'AWS Amplify',
    rn: 'React Native',
    vue: 'Vue.js',
    nuxt: 'Nuxt.js',
    vuex: 'Vuex',
    pinia: 'Pinia',
    angular: 'Angular',
    ionic: 'Ionic',
    capacitor: 'Capacitor',
    tailwind: 'TailwindCSS',
    webRTC: 'WebRTC',
    webSocket: 'WebSocket',
    webpack: 'Webpack',
    html5: 'HTML5',
    css: 'CSS',
    laravel: 'Larvel',
    djengo: 'Djengo',
    mySQL: 'MySQL',
    // 'MongoDB',
    graphQL: 'GraphQL',
    jQuery: 'jQuery',
    bootstrap: 'Bootstrap',
    ml: 'Multi-Language',
    sc: 'Subdomain & Custom Domain',
    wpPlugin: 'Wordpress Plugin',
    scss: 'SCSS',
}